# Generated by Django 3.2.13 on 2022-07-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(help_text='уникальный фрагмент url на основе наименования товара', max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='уникальный фрагмент url на основе наименования товара', max_length=255, verbose_name='url')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('quantity', models.PositiveSmallIntegerField(null=True, verbose_name='количество товара')),
                ('availability', models.BooleanField(default=True, verbose_name='в наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата и время обновления')),
                ('category', models.ManyToManyField(related_name='products', to='app_goods.Category', verbose_name='категория')),
                ('shop', models.ManyToManyField(related_name='products', to='app_shops.Shop', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'db_table': 'goods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='изображение товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='app_goods.product', verbose_name='товар')),
            ],
        ),
    ]
