# Generated by Django 3.2.13 on 2022-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
