# Generated by Django 3.2.13 on 2022-07-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='наименование типа цены', max_length=200, verbose_name='наименование')),
                ('discount', models.PositiveSmallIntegerField(blank=True, help_text='скидка в %', null=True, verbose_name='скидка')),
                ('start_date', models.DateTimeField(help_text='дата и время начала действия скидки', verbose_name='начало акции')),
                ('end_date', models.DateTimeField(help_text='дата и время окончания действия скидки', verbose_name='конец акции')),
                ('active', models.BooleanField(default=False, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'тип цены',
                'verbose_name_plural': 'типы цен',
                'db_table': 'price_types',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена товара')),
                ('price_type', models.ForeignKey(help_text='связь с моделью PriceType', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app_goods.pricetype', verbose_name='тип цены')),
                ('product', models.ForeignKey(help_text='связь с моделью Product', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app_goods.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
                'db_table': 'prices',
            },
        ),
    ]
