# Generated by Django 3.2.13 on 2022-08-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_auto_20220819_1811'),
        ('app_goods', '0002_auto_20220813_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(help_text='вид скидки', max_length=50, verbose_name='вид скидки')),
                ('discount_value', models.PositiveSmallIntegerField(blank=True, default=0, help_text='скидка в %', null=True, verbose_name='скидка')),
                ('description', models.TextField(blank=True, verbose_name='описание скидки')),
                ('start_date', models.DateTimeField(blank=True, help_text='дата и время начала действия скидки', null=True, verbose_name='начало акции')),
                ('end_date', models.DateTimeField(blank=True, help_text='дата и время окончания действия скидки', null=True, verbose_name='конец акции')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'db_table': 'discounts',
            },
        ),
        migrations.DeleteModel(
            name='PriceType',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='связь с моделью Discount', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_goods.discount', verbose_name='скидка'),
        ),
    ]
