# Generated by Django 3.2.13 on 2022-07-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_price_pricetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AddField(
            model_name='pricetype',
            name='product',
            field=models.ForeignKey(help_text='связь с моделью Product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='app_goods.product', verbose_name='товар'),
        ),
    ]
