# Generated by Django 3.2.13 on 2022-08-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_auto_20220819_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.FileField(default='/Users/shaikhutdinovdinar/PycharmProjects/python_django_group_flow11/marketplace/media/icons/categories/test_category_icon.jpg', upload_to='icons/categories/', verbose_name='иконка категории'),
        ),
    ]
