# Generated by Django 3.2.13 on 2022-07-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_auto_20220728_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='product',
            field=models.ForeignKey(help_text='связь с моделью Product', on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='app_goods.product', verbose_name='товар'),
        ),
    ]
