# Generated by Django 3.2.13 on 2022-07-28 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_alter_pricetype_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.ForeignKey(help_text='связь с моделью PriceType', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_goods.pricetype', verbose_name='тип цены'),
        ),
    ]
