# Generated by Django 3.2.13 on 2022-08-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(default=0, help_text='связь с моделью Discount', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_goods.discount', verbose_name='скидка'),
        ),
    ]
