# Generated by Django 3.2.13 on 2022-09-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_alter_category_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.FileField(default='/Users/shaikhutdinovdinar/PycharmProjects/python_django_group_flow11/marketplace/media/icons/categories/test_category_icon.jpg', upload_to='icons/categories/', verbose_name='иконка категории'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='app_goods.product', verbose_name='товар'),
        ),
    ]
