# Generated by Django 3.2.13 on 2022-09-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_alter_productimage_product'),
        ('app_goods', '0006_auto_20220904_1013'),
    ]

    operations = [
    ]
