# Generated by Django 3.2.13 on 2022-07-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_auto_20220728_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена товара со скидкой'),
        ),
        migrations.AlterField(
            model_name='price',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='базовая цена товара', max_digits=10, verbose_name='цена товара'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='скидка в %', null=True, verbose_name='скидка'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='дата и время окончания действия скидки', null=True, verbose_name='конец акции'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='дата и время начала действия скидки', null=True, verbose_name='начало акции'),
        ),
    ]
