# Generated by Django 3.2.13 on 2022-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_auto_20220729_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='вид сзади'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='main_image',
            field=models.ImageField(blank=True, help_text='основное изображение товара', null=True, upload_to='product_image/', verbose_name='изображение товара'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='вид сбоку'),
        ),
        migrations.AlterField(
            model_name='price',
            name='discounted_price',
            field=models.FloatField(default=0, verbose_name='цена товара со скидкой'),
        ),
    ]
