# Generated by Django 3.2.13 on 2022-09-26 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_goods', '0008_alter_category_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'На товар/категорию'), ('2', 'На набор'), ('3', 'На корзину')], default='Не оплачено', max_length=50, verbose_name='Статусы оплаты')),
            ],
            options={
                'verbose_name': 'тип скидки',
                'verbose_name_plural': 'типы скидок',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'product_image', 'verbose_name_plural': 'product_images'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='category image', null=True, upload_to='cat_image/', verbose_name='category_image'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='relationship with the Discount model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='app_goods.discount', verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='app_goods.category', verbose_name='parent category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='app_goods.category', verbose_name='parent category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Скидка на корзину', null=True, verbose_name='Количество необходимое в корзине'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(default=1, help_text='название скидки', max_length=50, verbose_name='discount_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_name_en',
            field=models.CharField(help_text='название скидки', max_length=50, null=True, verbose_name='discount_name'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_name_ru',
            field=models.CharField(help_text='название скидки', max_length=50, null=True, verbose_name='discount_name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_doublet',
            field=models.BooleanField(default=False, help_text='Скидка на набор', verbose_name='Сделать скидку при совпадении?'),
        ),
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='limited_edition'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_specs',
            field=models.JSONField(default=dict, verbose_name='список технических характеристик товара'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_en',
            field=models.TextField(max_length=5000, null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(max_length=5000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.FileField(default='E:\\Python\\python_django_group_diploma\\marketplace\\media\\icons\\categories\\test_category_icon.jpg', upload_to='icons/categories/', verbose_name='category icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='app_goods.category', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='unique url fragment based on the category name', max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='скидка в %', null=True, verbose_name='discount_value'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='discount end date and time', null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='discount start date and time', null=True, verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='app_goods.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='relationship with the Discount model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='app_goods.discount', verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='sales_count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='unique url fragment based on the product name', max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='views_count'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='back_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='main_image',
            field=models.ImageField(blank=True, help_text='main product image', null=True, upload_to='product_image/', verbose_name='main_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='app_goods.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/', verbose_name='side_image'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_goods.discounttype', verbose_name='discount_type'),
        ),
    ]
