# Generated by Django 3.2.13 on 2022-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_auto_20220926_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.FileField(default='/Users/shaikhutdinovdinar/PycharmProjects/python_django_group_flow11/marketplace/media/icons/categories/test_category_icon.jpg', upload_to='icons/categories/', verbose_name='category icon'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('product', models.ManyToManyField(related_name='tags', to='app_goods.Product')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
    ]
