# Generated by Django 3.2.13 on 2022-07-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_auto_20220729_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'изображение товара', 'verbose_name_plural': 'изображения товаров'},
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
