# Generated by Django 3.2.13 on 2022-07-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0009_auto_20220729_1703'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
    ]
