# Generated by Django 3.2.13 on 2022-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0010_alter_productimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена товара со скидкой'),
        ),
    ]
