# Generated by Django 3.2.13 on 2022-08-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказы', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_goods',
            field=models.JSONField(default=dict, verbose_name='список товаров заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_error',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='текст ошибки, возникшей при оплате'),
        ),
        migrations.AddField(
            model_name='order',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='app_order_order',
        ),
    ]
