# Generated by Django 3.2.13 on 2022-09-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_auto_20220910_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_error',
            new_name='payment_status',
        ),
    ]
