# Generated by Django 3.2.13 on 2022-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_rename_payment_error_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='title',
            field=models.CharField(choices=[('1', 'Доставка'), ('2', 'Экспресс-Доставка')], default='Доставка', max_length=30, verbose_name='delivery option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=30, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_order.delivery', verbose_name='delivery option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='order_comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_goods',
            field=models.JSONField(default=dict, verbose_name='list of order items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_order.paymethod', verbose_name='payment option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='the text of the error that occurred during the payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='title',
            field=models.CharField(choices=[('1', 'Онлайн картой'), ('2', 'Онлайн со случайного чужого счёта')], default='Онлайн картой', max_length=50, verbose_name='payment option'),
        ),
    ]
