# Generated by Django 3.2.13 on 2022-09-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_rename_payment_error_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='статус оплаты'),
        ),
    ]
