# Generated by Django 3.2.13 on 2022-08-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_shops', '0003_auto_20220819_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_express_coast', models.PositiveIntegerField()),
                ('min_order', models.PositiveIntegerField()),
                ('delivery_min', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import/', verbose_name='файл импорта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата импорта')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shops.shop')),
            ],
        ),
    ]
