# Generated by Django 3.2.13 on 2022-08-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_goods', '0003_auto_20220819_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(help_text='не null если покупатель авторизован', null=True, verbose_name='id покупателя')),
                ('session_id', models.CharField(help_text='связь корзины с анонимным покупателем', max_length=55, null=True, verbose_name='id сессии')),
                ('shop', models.CharField(blank=True, help_text='название выбранного магазина', max_length=255, null=True, verbose_name='магазин')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='цена товара')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления товара')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.product', verbose_name='id товара')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'товары в корзине',
                'db_table': 'cart_model',
                'ordering': ('added_at',),
            },
        ),
    ]
