# Generated by Django 3.2.13 on 2022-08-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='cart_model',
        ),
    ]
