# Generated by Django 3.2.13 on 2022-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='published',
            field=models.BooleanField(default=True, verbose_name='видимость/не оплачено'),
        ),
    ]
