# Generated by Django 3.2.13 on 2022-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_auto_20220926_1200'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'ordering': ('added_at',), 'verbose_name': 'cart item', 'verbose_name_plural': 'cart items'},
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added_at'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='session_id',
            field=models.CharField(help_text='cart relationship with an anonymous customer', max_length=55, null=True, verbose_name='session_id'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='shop',
            field=models.CharField(blank=True, help_text='name of the selected store', max_length=255, null=True, verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='user',
            field=models.IntegerField(help_text='not null if the customer is authorized', null=True, verbose_name='user'),
        ),
    ]
