# Generated by Django 3.2.13 on 2022-10-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220926_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='published',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
    ]
