# Generated by Django 3.2.13 on 2022-09-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='published',
        ),
    ]
