# Generated by Django 3.2.13 on 2022-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220815_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='shop',
            field=models.IntegerField(null=True, verbose_name='id магазина'),
        ),
    ]
