# Generated by Django 3.2.13 on 2022-08-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitems_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='shop',
        ),
    ]
