# Generated by Django 3.2.13 on 2022-09-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220926_1200'),
        ('cart', '0004_cartitems_published'),
    ]

    operations = [
    ]
