# Generated by Django 3.2.13 on 2022-09-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_merge_20220929_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='published',
        ),
    ]
