# Generated by Django 3.2.13 on 2022-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitems_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='shop',
            field=models.CharField(blank=True, help_text='название выбранного магазина', max_length=255, null=True, verbose_name='магазин'),
        ),
    ]
