# Generated by Django 3.2.13 on 2022-08-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='price_type',
        ),
    ]
