# Generated by Django 3.2.13 on 2022-08-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_shopproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='old_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='price_type',
        ),
    ]
