# Generated by Django 3.2.13 on 2022-08-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_remove_shopproduct_price_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='old_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='current_price',
        ),
    ]
