# Generated by Django 3.2.13 on 2022-10-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0010_alter_category_category_icon'),
        ('app_shops', '0004_alter_shopproduct_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'product in the store', 'verbose_name_plural': 'products in the stores'},
        ),
        migrations.AddField(
            model_name='shop',
            name='about',
            field=models.TextField(blank=True, verbose_name='about shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='about shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='about shop'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='e_mail_1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e_mail_1'),
        ),
        migrations.AddField(
            model_name='shop',
            name='e_mail_2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e_mail_2'),
        ),
        migrations.AddField(
            model_name='shop',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='house_number'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_1',
            field=models.CharField(blank=True, max_length=12, verbose_name='phone_1'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_2',
            field=models.CharField(blank=True, max_length=12, verbose_name='phone_2'),
        ),
        migrations.AddField(
            model_name='shop',
            name='post_index',
            field=models.CharField(blank=True, max_length=15, verbose_name='post_index'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(help_text='unique url fragment based on the shop name', max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is_available'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price without discount', max_digits=10, null=True, verbose_name='base price'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(help_text='relationship with the Product model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='app_goods.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='quantity of goods in the store', null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(help_text='relationship with the Shop model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='app_shops.shop', verbose_name='shop'),
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='shop image', null=True, upload_to='shop_image/', verbose_name='image')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='app_shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'shop image',
                'verbose_name_plural': 'shop images',
                'db_table': 'shop_images',
            },
        ),
    ]
