# Generated by Django 3.2.13 on 2022-08-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_order', '0002_auto_20220825_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Не оплачено'), ('2', 'Оплачено'), ('3', 'Ошибка оплаты - time_out'), ('4', 'Ошибка оплаты - err 35653'), ('5', 'Ошибка оплаты - err 999')], default='Не оплачено', max_length=50, verbose_name='Статусы оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('card_num', models.SmallIntegerField(default=0, verbose_name='card_num')),
                ('payment_amount', models.FloatField(default=0, verbose_name='payment_amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_order.order')),
                ('payment_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_payment.paystatus', verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
