# Generated by Django 3.2.13 on 2022-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_payment.paystatus', verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='paystatus',
            name='title',
            field=models.CharField(choices=[('1', 'Не оплачено'), ('2', 'Оплачено'), ('3', 'Ошибка оплаты - time_out'), ('4', 'Ошибка оплаты - err 35653'), ('5', 'Ошибка оплаты - err 999')], default='Не оплачено', max_length=50, verbose_name='payment statuses'),
        ),
    ]
