# Generated by Django 3.2.13 on 2022-07-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Номер телефона пользователя максимальной длиной в 12 символов', max_length=12, verbose_name='номер телефона')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Баланс пользователя, максимально возможное число: 99999999.99', max_digits=10, verbose_name='баланс')),
                ('user', models.OneToOneField(help_text='Связь с моделью пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(help_text='Поле для сохранения аватарки пользователя', upload_to='avatars', verbose_name='аватарка')),
                ('profile', models.OneToOneField(help_text='Связь с моделью профиля пользователя', on_delete=django.db.models.deletion.CASCADE, to='app_users.profile', verbose_name='профиль')),
            ],
        ),
    ]
