# Generated by Django 3.2.13 on 2022-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20220813_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='image',
            name='avatar',
            field=models.ImageField(default='default.jpg', help_text='Поле для сохранения аватарки пользователя', upload_to='avatars', verbose_name='аватарка'),
        ),
    ]
