# Generated by Django 3.2.13 on 2022-09-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_auto_20220819_1811'),
        ('app_users', '0004_profile_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер банковской карточки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recent_views',
            field=models.ManyToManyField(to='app_shops.ShopProduct'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='ViewsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.profile')),
                ('shop_product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_shops.shopproduct')),
            ],
        ),
    ]
