# Generated by Django 3.2.13 on 2022-09-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_alter_category_category_icon'),
        ('app_users', '0005_auto_20220910_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewshistory',
            name='shop_product',
        ),
        migrations.AddField(
            model_name='viewshistory',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_goods.product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_views',
            field=models.ManyToManyField(blank=True, to='app_goods.Product'),
        ),
    ]
